apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-deployment
  # Not Required but recommended
  name: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
  spec:
    containers:
    - name: mycontainer
      image: <my-image>:tag
      imagePullPolicy: <Always|IfNotPresent>
      port:
      - name: http
        containerPort: 80
      - name: http-service
        containerPort: 8080
      resources:
        # Resources needed to fire up container
        requests:
          memory: "100Mi"
          cpu: "100m"
        # Container will be restarted if it exceeds these values
        limits:
          memory: "500Mi"
          cpu: "250m"
      env:
      # Envinment variables to be inserted at container
      - name: ENV
        value: "production"
      readinessProbe:
        httpGet:
          path: /
          port: http
        initialDelaySeconds: 15
        periodSeconds: 5
      livenessProbe:
        tcpSocket:
          port: http-service
        initialDelaySeconds: 30
        periodSeconds: 5
    # Needed to pull images from private registry
    imagePullSecrets:
    # It is a secret object on the same namespace
    - name: secret-name
