apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  # Not Required but recommended
  name: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
  spec:
    containers:
    - name: mycontainer
      image: <my-image>:tag
      port:
      - containerPort: 80
