apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: ClusterIP
  ClusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
