apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcp-pv
spec:
  storageClassName: "gcp-hdd"
  capacity:
    storage: 10G
  accessModes:
    - <ReadWriteOnce|ReadOnlyMany>
  gcePersistentDisk:
    # You have to create the persistent disk at the GCP
    pdName: pd-name
    fsType: ext4
